### ISSUE TITLE
Organise Tuesday

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/ClashOfORGroups#1]
@geraintpalmer will CC you in an email before end of day.

**Comment by drvinceknight** [comment]
Have CC'd @geraintpalmer in to email to Iza.

**Comment by drvinceknight** [comment]
Looks like will only be an afternoon visit.

I could now drive, will need 2 cars: can you be the other one @geraintpalmer?

**Comment by geraintpalmer** [comment]
I'm happy to drive

**Comment by drvinceknight** [comment]
See 113f07f8d4520c087fc0e481251eb974c087750b

**Comment by drvinceknight** [comment]
Danny has meeting in his diary for 1030. It will be a combination of you and me/iza driving.
