### ISSUE TITLE
Sort out wifi

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/ClashOfORGroups#4]
@JasYoung314 can you speak to Paul Jewell about getting guest wifi codes for our guests.

**Comment by drvinceknight** [comment]
(They might have access to eduroam but worth having backup)

**Comment by JasYoung315** [comment]
Spoken to Mike. He said that we can get Wifi codes whenever, but to leave it till next week in case they expire.

**Comment by drvinceknight** [comment]
Reopening just so that we remember to get them.

**Comment by drvinceknight** [comment]
I have been emailed codes and passwords. Will send to you both also.
