### ISSUE TITLE
Book lunch for Monday

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/ClashOfORGroups#5]
I think getting a cheap buffet in for the Monday is fine. Let's see what Paul thinks in meeting on Monday.

Decide who wants to pick this up: @JasYoung314 @geraintpalmer

**Comment by drvinceknight** [comment]
Need to discuss with Paul that there are funds.

**Comment by drvinceknight** [comment]
This depends on #2

**Comment by JasYoung315** [comment]
Lunch at 1230 in Aberdare hall for 8 people

**Comment by JasYoung314** [comment]
and Lunch on tuesday is buffet in m102 at 1300

**Comment by JasYoung315** [comment]
I've just had an email saying that Aberdare is only doing bar food until the 20th (not the usual carvery). This includes things like jacket potatoes, salads pies, lasagnes etc. Is this still okay?

**Comment by geraintpalmer** [comment]
Fine by me

**Comment by drvinceknight** [comment]
A long way to go for a basic lunch? Could go closer to here or just get a
buffet?

**Comment by JasYoung315** [comment]
I think it's fine, but I can book a buffet for both days if you prefer

**Comment by drvinceknight** [comment]
As discussed in the hangout: go with Aberdare if you prefer.

**Comment by JasYoung315** [comment]
We have decided to stick with Aberdare
