### ISSUE TITLE
Finalise schedule

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/ClashOfORGroups#7]
Waiting on confirmation of potential start time and indeed if Monday is at all ok for meeting with the Dutch group. Otherwise could have ABCi visit on Monday pm (although a shame as everyone would still be getting to know each other) with talks/discussion on the Tuesday.

**Comment by drvinceknight** [comment]
Following email have rejigged the schedule: 807ad205c8b68e4d4ade2f2e60ce025218dc9b79

**Comment by JasYoung315** [comment]
Final tweaks to
Tuesday: 5178de688f7ecd900817ec33a5e8018769def303
Monday: 4543d78dc8ea0bb1d15a5ae897319b9f199bbd31
