### ISSUE TITLE
Monday Evening Meal

### ISSUE THREAD

**Issue by JasYoung315** [drvinceknight/ClashOfORGroups#9]
- [ ] Decide on location
- [ ] Check that location is suitable
- [ ] Book table

**Comment by drvinceknight** [comment]
Invite MSc students to dinner.

**Comment by geraintpalmer** [comment]
A invite has been sent

**Comment by geraintpalmer** [comment]
Sam is coming

**Comment by geraintpalmer** [comment]
Smokehaus booked for 7pm for 7 people

**Comment by drvinceknight** [comment]
Is that because (not Sam) can't make it? Worth booking for 8 if you haven't heard from him?

(Close the issue)

**Comment by geraintpalmer** [comment]
Josh can make it. Did I count wrong? 2 MSc students, 3 Dutch people, Me and Jason, 7 right?

**Comment by geraintpalmer** [comment]
Are you coming? I thought you said you'd rather not, sorry

**Comment by drvinceknight** [comment]
Ah: no it's 4 dutch people now. Their names are on the monday schedule.
Have you spoken with Jason about this? I know he looked in to the clink...

**Comment by drvinceknight** [comment]
> Are you coming? I thought you said you'd rather not, sorry

Lol, no I'm fine :) :+1:

**Comment by geraintpalmer** [comment]
Yes spoken to Jason. I'll change it to 8 then.

**Comment by drvinceknight** [comment]
Cool.

**Comment by drvinceknight** [comment]
> I'll change it to 8 then.

When you have: close the issue.
